/** Permission keys copied onto every new organization. Platform-only keys stay off org roles. */
export const PLATFORM_ONLY_PERMISSIONS = ["organizations:manage"];

export const DEFAULT_ORG_ROLES: Record<
  string,
  { description: string; permissions: string[] | "*"; isSystem: boolean }
> = {
  ORG_OWNER: {
    description: "Organization owner. Full control inside this company.",
    permissions: "*",
    isSystem: true,
  },
  ORG_ADMIN: {
    description:
      "Organization administrator. Manages people, departments, and settings.",
    permissions: [
      "users:create",
      "users:view",
      "users:manage",
      "users:manage_permissions",
      "users:assign_roles",
      "users:reset_password",
      "roles:view",
      "roles:manage",
      "departments:view",
      "departments:manage",
      "branches:view",
      "branches:manage",
      "invitations:manage",
      "attendance:view_all",
      "attendance:export",
      "attendance:review",
      "attendance:manage_exemption",
      "requests:view_all",
      "requests:approve",
      "projects:create",
      "projects:update",
      "projects:update_status",
      "projects:manage_members",
      "projects:delete",
      "tasks:create",
      "tasks:assign",
      "tasks:update_status",
      "tasks:manage_status",
      "tasks:manage",
      "tasks:edit",
      "tasks:delete",
      "uploads:create",
      "uploads:view_all",
      "uploads:manage",
      "events:manage",
      "suggestions:manage",
      "activities:view_all",
      "screentime:view_all",
    ],
    isSystem: true,
  },
  EXECUTIVE: {
    description: "Executive visibility and approvals.",
    permissions: [
      "users:view",
      "roles:view",
      "departments:view",
      "branches:view",
      "attendance:view_all",
      "attendance:export",
      "attendance:review",
      "requests:view_all",
      "requests:approve",
      "uploads:view_all",
      "uploads:create",
      "activities:view_all",
      "screentime:view_all",
      "projects:update_status",
    ],
    isSystem: true,
  },
  STAFF: {
    description: "Standard staff member.",
    permissions: [
      "users:view",
      "projects:create",
      "tasks:create",
      "tasks:edit",
      "tasks:update_status",
      "uploads:create",
    ],
    isSystem: true,
  },
};
